{
    "data":[{
    "group":"A",
    "items":[{
            "country":"俄罗斯","abbr":"rus","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
        },
        {
            "country":"埃及","abbr":"egy","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
        },
        {
            "country":"乌拉圭","abbr":"uru","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
        },
        {
            "country":"沙特阿拉伯","abbr":"sar","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
        }
    ]
    },
    {
        "group":"B",
        "items":[{
                "country":"摩洛哥","abbr":"mar","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"葡萄牙","abbr":"por","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"伊朗","abbr":"iri","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"西班牙","abbr":"esp","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            }
        ]
    },
    {
        "group":"C",
        "items":[{
                "country":"法国","abbr":"fra","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"秘鲁","abbr":"per","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"丹麦","abbr":"den","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"澳大利亚","abbr":"aus","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            }
        ]
    },
    {
        "group":"D",
        "items":[{
                "country":"阿根廷","abbr":"arg","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"克罗地亚","abbr":"cro","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"尼日利亚","abbr":"ngr","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"冰岛","abbr":"isl","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            }
        ]
    },
    {
        "group":"E",
        "items":[{
                "country":"哥斯达黎加","abbr":"crc","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"巴西","abbr":"bra","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"塞尔维亚","abbr":"sbr","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"瑞士","abbr":"sui","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            }
        ]
    },
    {
        "group":"F",
        "items":[{
                "country":"德国","abbr":"ger","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"瑞典","abbr":"swe","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"韩国","abbr":"kor","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"墨西哥","abbr":"mex","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            }
        ]
    },
    {
        "group":"G",
        "items":[{
                "country":"比利时","abbr":"bel","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"突尼斯","abbr":"tun","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"英格兰","abbr":"gbr","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"巴拿马","abbr":"pan","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            }
        ]
    },
    {
        "group":"H",
        "items":[{
                "country":"哥伦比亚","abbr":"col","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"波兰","abbr":"pol","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"日本","abbr":"jpn","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            },
            {
                "country":"塞内加尔","abbr":"sen","session":"3","win":"1","tie":"1","lost":"1","score":"4","fumble":"3","netball":"1","point":"4"
            }
        ]
    },
    {
        "items":[{
                "name":"罗德里格斯","country":"哥伦比亚","abbr":"col","score":"7"
            },
            {
                "name":"穆勒","country":"波兰","abbr":"pol","score":"6"
            },
            {
                "name":"内马尔","country":"日本","abbr":"jpn","score":"5"
            },
            {
                "name":"梅西","country":"塞内加尔","abbr":"sen","score":"4"
            },
            {
                "name":"范佩西","country":"塞内加尔","abbr":"sen","score":"3"
            },
            {
                "name":"本泽马","country":"塞内加尔","abbr":"sen","score":"2"
            },
            {
                "name":"许尔勒","country":"塞内加尔","abbr":"sen","score":"1"
            },
            {
                "name":"帕帕斯塔索普洛斯","country":"塞内加尔","abbr":"sen","score":"0"
            },
            {
                "name":"梅西","country":"塞内加尔","abbr":"sen","score":"4"
            },
            {
                "name":"范佩西","country":"塞内加尔","abbr":"sen","score":"3"
            },
            {
                "name":"本泽马","country":"塞内加尔","abbr":"sen","score":"2"
            },
            {
                "name":"许尔勒","country":"塞内加尔","abbr":"sen","score":"1"
            },
            {
                "name":"帕帕斯塔索普洛斯","country":"塞内加尔","abbr":"sen","score":"0"
            }
        ]
    }
]}